# coding: utf-8

from __future__ import absolute_import
from evechem_api.models.link import Link
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Equipment(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, contains: int=None, id: int=None, type: int=None, online: bool=None, inputs: List[Link]=None, last_updated: int=None, outputs: List[Link]=None, resource: int=None, name: str=None):
        """
        Equipment - a model defined in Swagger

        :param contains: The contains of this Equipment.
        :type contains: int
        :param id: The id of this Equipment.
        :type id: int
        :param type: The type of this Equipment.
        :type type: int
        :param online: The online of this Equipment.
        :type online: bool
        :param inputs: The inputs of this Equipment.
        :type inputs: List[Link]
        :param last_updated: The last_updated of this Equipment.
        :type last_updated: int
        :param outputs: The outputs of this Equipment.
        :type outputs: List[Link]
        :param resource: The resource of this Equipment.
        :type resource: int
        :param name: The name of this Equipment.
        :type name: str
        """
        self.swagger_types = {
            'contains': int,
            'id': int,
            'type': int,
            'online': bool,
            'inputs': List[Link],
            'last_updated': int,
            'outputs': List[Link],
            'resource': int,
            'name': str
        }

        self.attribute_map = {
            'contains': 'contains',
            'id': 'id',
            'type': 'type',
            'online': 'online',
            'inputs': 'inputs',
            'last_updated': 'last_updated',
            'outputs': 'outputs',
            'resource': 'resource',
            'name': 'name'
        }

        self._contains = contains
        self._id = id
        self._type = type
        self._online = online
        self._inputs = inputs
        self._last_updated = last_updated
        self._outputs = outputs
        self._resource = resource
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Equipment':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The equipment of this Equipment.
        :rtype: Equipment
        """
        return deserialize_model(dikt, cls)

    @property
    def contains(self) -> int:
        """
        Gets the contains of this Equipment.
        Quantity of material stored when last updated. 

        :return: The contains of this Equipment.
        :rtype: int
        """
        return self._contains

    @contains.setter
    def contains(self, contains: int):
        """
        Sets the contains of this Equipment.
        Quantity of material stored when last updated. 

        :param contains: The contains of this Equipment.
        :type contains: int
        """

        self._contains = contains

    @property
    def name(self) -> str:
        """
        Gets the name of this Equipment.

        :return: The name of this Equipment.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Equipment.

        :param name: The name of this Equipment.
        :type name: str
        """

        self._name = name


    @property
    def id(self) -> int:
        """
        Gets the id of this Equipment.
        Unique id number for this equipment. 

        :return: The id of this Equipment.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this Equipment.
        Unique id number for this equipment. 

        :param id: The id of this Equipment.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def type(self) -> int:
        """
        Gets the type of this Equipment.
        Type number for this equipment. 

        :return: The type of this Equipment.
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type: int):
        """
        Sets the type of this Equipment.
        Type number for this equipment. 

        :param type: The type of this Equipment.
        :type type: int
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def online(self) -> bool:
        """
        Gets the online of this Equipment.
        If the equipment is online or offline. 

        :return: The online of this Equipment.
        :rtype: bool
        """
        return self._online

    @online.setter
    def online(self, online: bool):
        """
        Sets the online of this Equipment.
        If the equipment is online or offline. 

        :param online: The online of this Equipment.
        :type online: bool
        """

        self._online = online

    @property
    def inputs(self) -> List[Link]:
        """
        Gets the inputs of this Equipment.
        Array of input links. 

        :return: The inputs of this Equipment.
        :rtype: List[Link]
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs: List[Link]):
        """
        Sets the inputs of this Equipment.
        Array of input links. 

        :param inputs: The inputs of this Equipment.
        :type inputs: List[Link]
        """

        self._inputs = inputs

    @property
    def last_updated(self) -> int:
        """
        Gets the last_updated of this Equipment.

        :return: The last_updated of this Equipment.
        :rtype: int
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated: int):
        """
        Sets the last_updated of this Equipment.

        :param last_updated: The last_updated of this Equipment.
        :type last_updated: int
        """

        self._last_updated = last_updated

    @property
    def outputs(self) -> List[Link]:
        """
        Gets the outputs of this Equipment.
        Array of output links. 

        :return: The outputs of this Equipment.
        :rtype: List[Link]
        """
        return self._outputs

    @outputs.setter
    def outputs(self, outputs: List[Link]):
        """
        Sets the outputs of this Equipment.
        Array of output links. 

        :param outputs: The outputs of this Equipment.
        :type outputs: List[Link]
        """

        self._outputs = outputs

    @property
    def resource(self) -> int:
        """
        Gets the resource of this Equipment.
        type_id of material/reaction being stored/mined/processed in this equipment. 

        :return: The resource of this Equipment.
        :rtype: int
        """
        return self._resource

    @resource.setter
    def resource(self, resource: int):
        """
        Sets the resource of this Equipment.
        type_id of material/reaction being stored/mined/processed in this equipment. 

        :param resource: The resource of this Equipment.
        :type resource: int
        """
        if resource is None:
            raise ValueError("Invalid value for `resource`, must not be `None`")

        self._resource = resource

