# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class KeyUpdate(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, permission: str=None):
        """
        KeyUpdate - a model defined in Swagger

        :param name: The name of this KeyUpdate.
        :type name: str
        :param permission: The permission of this KeyUpdate.
        :type permission: str
        """
        self.swagger_types = {
            'name': str,
            'permission': str
        }

        self.attribute_map = {
            'name': 'name',
            'permission': 'permission'
        }

        self._name = name
        self._permission = permission

    @classmethod
    def from_dict(cls, dikt) -> 'KeyUpdate':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The key_update of this KeyUpdate.
        :rtype: KeyUpdate
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this KeyUpdate.

        :return: The name of this KeyUpdate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this KeyUpdate.

        :param name: The name of this KeyUpdate.
        :type name: str
        """

        self._name = name

    @property
    def permission(self) -> str:
        """
        Gets the permission of this KeyUpdate.

        :return: The permission of this KeyUpdate.
        :rtype: str
        """
        return self._permission

    @permission.setter
    def permission(self, permission: str):
        """
        Sets the permission of this KeyUpdate.

        :param permission: The permission of this KeyUpdate.
        :type permission: str
        """

        self._permission = permission

