# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class OperationName(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, public_name: str=None):
        """
        OperationName - a model defined in Swagger

        :param name: The name of this OperationName.
        :type name: str
        :param public_name: The public_name of this OperationName.
        :type public_name: str
        """
        self.swagger_types = {
            'name': str,
            'public_name': str
        }

        self.attribute_map = {
            'name': 'name',
            'public_name': 'public_name'
        }

        self._name = name
        self._public_name = public_name

    @classmethod
    def from_dict(cls, dikt) -> 'OperationName':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The operation_name of this OperationName.
        :rtype: OperationName
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this OperationName.

        :return: The name of this OperationName.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this OperationName.

        :param name: The name of this OperationName.
        :type name: str
        """

        self._name = name

    @property
    def public_name(self) -> str:
        """
        Gets the public_name of this OperationName.

        :return: The public_name of this OperationName.
        :rtype: str
        """
        return self._public_name

    @public_name.setter
    def public_name(self, public_name: str):
        """
        Sets the public_name of this OperationName.

        :param public_name: The public_name of this OperationName.
        :type public_name: str
        """

        self._public_name = public_name

